In [38]:
import pandas as pd
import numpy as np
import math
import scipy.stats.wilcoxon as wilcoxon

ModuleNotFoundError: No module named 'scipy.stats.wilcoxon'

In [26]:
df = pd.DataFrame({'before':[1,5,6,8,9,10], 'after': [2,4,12,14,18,20]})
df

   before  after
0       1      2
1       5      4
2       6     12
3       8     14
4       9     18
5      10     20

In [27]:
# нулевая гипотеза: интенсивность сдвигов в типичном направлении не превосходит интенсивности сдивгов в нетипичном
# альтернативная гипотеза: интенсивность сдвигов в типичном направлении превосходит интенсивности сдивгов в нетипичном

In [28]:
shifts = df['after'] - df['before']
df['shifts'] = shifts
df

   before  after  shifts
0       1      2       1
1       5      4      -1
2       6     12       6
3       8     14       6
4       9     18       9
5      10     20      10

In [30]:
df['abs_shifts'] = df['shifts'].abs()
df

   before  after  shifts  abs_shifts
0       1      2       1           1
1       5      4      -1           1
2       6     12       6           6
3       8     14       6           6
4       9     18       9           9
5      10     20      10          10

In [31]:
df.sort_values(by = 'abs_shifts')
df

   before  after  shifts  abs_shifts
0       1      2       1           1
1       5      4      -1           1
2       6     12       6           6
3       8     14       6           6
4       9     18       9           9
5      10     20      10          10

In [35]:
sum(df['abs_shifts'])
sum_1 = sum(df[df['shifts'] < 0]['abs_shifts'])
sum_2 = sum(df[df['shifts'] > 0]['abs_shifts'])
print(sum_1, sum_2)

1 32

In [37]:
df['abs_shifts'].rank(method = 'average')

0    1.5
1    1.5
2    3.5
3    3.5
4    5.0
5    6.0
Name: abs_shifts, dtype: float64